name: Scrape iFood BI Jobs and Email

on:
  schedule:
    - cron: '0 */4 * * *' 
  workflow_dispatch: 

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download previous jobs history # <--- NOVO PASSO
      uses: actions/download-artifact@v4
      with:
        name: bi-jobs-history
        path: . # Baixa o arquivo para a raiz do repositório
      continue-on-error: true # Permite que o workflow continue mesmo se o artefato não for encontrado (primeira execução)

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable fonts-liberation libnspr4 libnss3 lsb-release wget gnupg

    - name: Run scraper and send email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python main.py 

    - name: Upload current jobs history # <--- NOVO PASSO
      uses: actions/upload-artifact@v4
      with:
        name: bi-jobs-history
        path: previous_bi_jobs.json
