name: Scrape iFood BI Jobs and Email

on:
  schedule:
    - cron: '0 */4 * * *' # Roda a cada 4 horas
  workflow_dispatch: # Permite acionar manualmente o workflow

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest
    permissions:
      contents: write # <--- CRUCIAL: Adicionado para permitir commit/push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Necessário para a permissão de escrita

    - name: Debug - List repository root after checkout
      run: |
        echo "Conteúdo da raiz do repositório APÓS checkout:"
        pwd
        ls -la

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Google Chrome stable
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome-stable --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Usa requirements.txt diretamente da raiz

    - name: Check for previous_bi_jobs.json and create if not exists
      run: |
        if [ ! -f previous_bi_jobs.json ]; then
          echo "[]" > previous_bi_jobs.json
          echo "previous_bi_jobs.json criado como array JSON vazio."
        fi
        ls -l previous_bi_jobs.json

    - name: Run scraper and send email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        echo "Caminho atual para python main.py:"
        pwd
        python main.py # Executa o script principal diretamente da raiz

    - name: Commit updated previous_bi_jobs.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add previous_bi_jobs.json
        git commit -m "Atualiza histórico de vagas BI [skip ci]" || true # '|| true' evita falha se não houver mudanças
        git push
