name: Scrape iFood BI Jobs and Email

# Define quando o workflow será acionado
on:
  schedule:
    # Executa o workflow em um cronograma.
    # A sintaxe é 'minuto hora dia_do_mes mes dia_da_semana' (em UTC).
    # '0 11 * * *' significa às 11:00 UTC (Universal Coordinated Time) de cada dia.
    # Para você em Salvador (-3 GMT), isso seria 08:00 (8 AM) BRT.
    # Se quiser outro horário, ajuste o '11'. Por exemplo:
    # Para 9 AM BRT (Salvador), seria 12:00 UTC: '0 12 * * *'
    # Para 10 AM BRT (Salvador), seria 13:00 UTC: '0 13 * * *'
    - cron: '0 11 * * *' 
  
  # workflow_dispatch permite que você execute o workflow manualmente
  # pela interface do GitHub (na aba "Actions" do seu repositório).
  workflow_dispatch: 

# Define os trabalhos (jobs) a serem executados neste workflow
jobs:
  scrape_and_send:
    # O sistema operacional em que o trabalho será executado
    runs-on: ubuntu-latest

    # As etapas (steps) que o trabalho seguirá
    steps:
    - name: Checkout repository # Etapa para baixar o código do seu repositório
      uses: actions/checkout@v4

    - name: Set up Python # Etapa para configurar o ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Define a versão do Python a ser usada. Você pode ajustar para '3.10', '3.11', etc.

    - name: Install dependencies # Etapa para instalar as bibliotecas Python e o Chrome
      run: |
        # Atualiza o pip e instala as dependências do requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Instala o Google Chrome e dependências necessárias para o Selenium no Ubuntu
        # O webdriver-manager (configurado no seu main.py) irá baixar o ChromeDriver automaticamente.
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Incluí algumas outras libs que podem ser úteis para o Chrome Headless
        sudo apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libnspr4 libnss3 lsb-release xdg-utils wget gnupg

    - name: Run scraper and send email # Etapa para executar seu script Python
      # Define variáveis de ambiente para o script Python, puxando dos GitHub Secrets
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        # Executa o seu script principal
        python main.py
