name: Scrape iFood BI Jobs and Email

on:
  schedule:
    # Rodar a cada 4 horas.
    # Por exemplo, às 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC.
    - cron: '0 */4 * * *' # <-- ALTERADO PARA RODAR A CADA 4 HORAS
  workflow_dispatch: # Permite executar o workflow manualmente

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Use a versão do Python que preferir, e.g., '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # requirements.txt agora está na raiz do repositório
        pip install -r requirements.txt 

        # Instalar o Chrome e dependências essenciais
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable fonts-liberation libnspr4 libnss3 lsb-release wget gnupg

    - name: Run scraper and send email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        # main.py agora está na raiz do repositório
        python main.py
